### ISSUE TITLE
[O]llama support?

### ISSUE THREAD

**Issue by vrurg** [antononcube/Raku-LLM-Functions#1]
What do you think about adding support for locally running [o]llama? I'd be happy to see JSON prompt used with it. :)

**Comment by antononcube** [comment]
Of course, it is a good idea to support Llama. I think it is a good idea to make a separate package, named something like "WWW::Llama". Then the LLM functions of this package can be just use Llama access configurations.

**Comment by antononcube** [comment]
After reading the [Llama's documentation](https://github.com/Mozilla-Ocho/llamafile/blob/main/llama.cpp/server/README.md#api-endpoints) it looks like Llama uses an Web API that is OpenAI compatible. Hence, just proper extensions of ["WWW::OpenAI"](https://github.com/antononcube/Raku-WWW-OpenAI) have to be made to support Llama.

**Comment by vrurg** [comment]
People might get confused with naming.

Anyway, off-topic, but don't know where it's better to ask. What is the right way to attach a file to chat request? I mean, for `llm-vision` I found that `image-import` function and the parameter is there. But for textual synthesis?

**Comment by antononcube** [comment]
> People might get confused with naming.

Yes. After reading the Llama documentation some more I think there should be a  "WWW::Llama" package.


BTW, "WWW::OpenAI" can work with Llama already, and this package has/supports a 'llama' configuration.

> What is the right way to attach a file to chat request? I mean, for llm-vision I found that image-import function and the parameter is there. But for textual synthesis?


I assume you can just slurp and concatenate file's content. The function `llm-synthesize` also takes arrays of strings. (And concatenates them into one prompt.)

**Comment by vrurg** [comment]
> I assume you can just slurp and concatenate file's content. The function `llm-synthesize` also takes arrays of strings. (And concatenates them into one prompt.)

Works for small files. But I would like to analyze PDFs, for example. I'm getting promising results when submitting via their Web UI, but can't figure out how to do via API.

**Comment by antononcube** [comment]
There are some discrepancies between what: 

- OpenAI's documentation says 
- API can do
- Web Interface can do

I think in the use case you outlined -- feeding a large PDF file to an LLM -- you have to do one of the following:

1. Convert the PDF file to plain text and use a model that allows large number of tokens of the input (e.g. [128K](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo))
2. Convert the PDF file pages into images, and feed the images to one of OpenAI's vision models
3. Use the texts of the PDF file pages with a chat object, progressively feeding them to the LLM

I think 1) is the easiest option. 3) requires to learn how to use `llm-chat` -- should be [fairly easy](https://github.com/antononcube/Raku-LLM-Functions/blob/main/xt/09-MistralAI-chat.rakutest), but not as straightforward as `llm-synthesize`.

**Comment by antononcube** [comment]
The original request is implemented -- there is a dedicated "llama" configuration.

Here is example usage:

```raku
use LLM::Functions;
use LLM::Prompts;


my $prompt = llm-prompt("Yoda");
say $prompt;

say "-" x 120;
my $conf = llm-configuration('Llama', model => 'gpt-3.5-turbo');

my $chatObj = llm-chat($prompt, :$conf);

say $chatObj.eval("Who are you?" ~ llm-prompt('Translate')('German'));
```

----

 LLMs of ["llamafile"](https://github.com/mozilla-Ocho/llamafile?tab=readme-ov-file#other-example-llamafiles) can be used via "WWW:OpenAI" by providing suitable base URL. This what the current implementation uses. Configuration-wise and function-wise nothing will change when the dedicated access package "WWW::LlamaFile" is implemented.

**Comment by vrurg** [comment]
So, for now it's chat only? No way of attaching a file to message yet?

**Comment by vrurg** [comment]
Anyway, thank you!

**Comment by antononcube** [comment]
> So, for now it's chat only? No way of attaching a file to message yet?

I am not sure should file-attachment be implemented for the functions of this package. It might be a good idea, but ultimately the file content is serialized at some point, so I would rather send those serializations with `llm-synthesize` and co.

----

As for the original request -- using llamafile models -- I am [working on it](https://github.com/antononcube/Raku-WWW-LLaMA). And if file attachment is part of [any of API's endpoints](https://github.com/Mozilla-Ocho/llamafile/blob/main/llama.cpp/server/README.md#api-endpoints), then I will include it.


----

What are the files sizes you are dealing with? (Say, of a PDF file you would attach to the message to the LLM.)

**Comment by vrurg** [comment]
It's doesn't really matter which way I do it. I'm not well familiar with the structure of the related packages, so might be asking dumb questions. :)

There is no particular limits on the kinds of files. So far, PDFs are likely. Might submit emails for estimating scam content probabilities. A side project is to wait until they get llava model support fixed and try attaching keywords/descriptions to images for better OS-level search.

**Comment by antononcube** [comment]
Bot LLaMA and Ollama are supported at this point.
